[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "webmax"
version = "0.1.0"
description = "Web Max API client"
dependencies = [
    "websockets"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"